repos:
  # General file checks (file size, end of files, trailing whitespace)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [--remove-all-unused-imports, --in-place]

  # Import Sorting (Isort)
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Code Formatting (Black)
  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black

  # Type Checking (Mypy)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.0 # Use the latest stable version
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: ["--strict"]

  # # ðŸ§ª Local Hook for Running Pytest
  # - repo: local
  #   hooks:
  #     - id: run-pytest
  #       name: Run Pytest Tests
  #       # Define the command to execute
  #       entry: pytest
  #       # The language 'system' uses the pytest installed in your virtual environment
  #       language: system
  #       # Run only on Python files or all files, depending on your test structure
  #       types: [python]
  #       # Setting 'pass_filenames: false' makes pytest run all tests
  #       # instead of only those related to modified files.
  #       pass_filenames: false
